#! /bin/bash

printf "Vérification que CMake est bien installé... "

if command -v cmake >/dev/null; then
	echo "CMake installé!"
else
	echo "CMake non installé, lancement de APT"
	echo "sudo apt install cmake"
	sudo apt install cmake
fi

echo "Lancement du build"
echo "cmake -S ./ -B build/"
cmake -S ./ -B build/

echo "cd build"
cd build
echo "make"
if make; then
	echo "Succès! Résultat dans build/LiDAR_UST10LX"
else
	echo "Echec"
fi
